apiVersion: v1
kind: Service
metadata:
  name: fastapi-yaml
  namespace: fastapi-yaml
spec:
  selector:
    app: fastapi-yaml
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP